### ISSUE TITLE
Briefly describe the dataset and the variables that you will visualize

### ISSUE THREAD

**Issue by SonQBChau** [UBC-MDS/gapminder_challenge#4]
- Climate Action:
 1. TBC
 2. TBC

- Gender equality:
 1. Up to 1990, 18 countries in the world had been led by a female head of state or government. What was that number in 2021? 
 2. How many companies in the world have a woman as top manager or CEO?

**Comment by SonQBChau** [comment]
I suspected that these surveys might have a different source of data too. I don't think it's a big problem as we can always come up with new questions.
For the data, any subset of gapminder is fine. We don't need to make it's complicated, but I do think we should make it interesting

**Comment by imtvwy** [comment]
As each of us will implement one plot in later milestone, maybe we can all draft a question based on the above 'summary gapminder dataset' and propose the interaction component as well?  Then, we can based on the finalized questions to draft the proposals.

**Comment by imtvwy** [comment]
Question 1 (Vanessa) :  The average number of children per woman in 1990 is 4.05, what is the average number in 2018? Ans: 2.74
Sample Plot: 
![image](https://user-images.githubusercontent.com/67822947/154184203-5811ec01-9eb7-46e9-a2f1-30bb4121b01b.png)
Intereaction:
By year range:  1900-2018
By color: none, region, income group

**Comment by BooleanJulien** [comment]
I like this plan:

My question might be: In 1980, the difference in average life expectancy between European and Sub-saharan African countries was X years. What was it in 2018?

Plot: 
- Axes: Year range between 1980 and 2018 vs. life expectancy (num years)
- Content: Lines for each country, coloured by region and average lines (maybe split into two charts)
Interactivity:

- Tooltips for each country
- filters for sub-regions
- filters for time period
- filters for within-region GDP percentiles?

**Comment by SonQBChau** [comment]
Here is my take on this:
- Our theme would be education and misconception, I would try to frame the questions around it.
- I would try to avoid asking for specific numbers (e.g what will be in 2018), but rather than asking for what the audience believes. 
- For example, Vanessa's question can be: the average number of children per woman in Western countries was 2 times lower than Asian countries. What will be the ratio now? 1. Still double. 2. About 50% 3. The same. That way, the user can guess before they explore our graph
- I think Julien's question is excellence, with minor improvement like instead of asking for X years, we replace with friendly stats like percentage or increase-decrease gap.

> do you think rough drafts of the plot like Vanessa made are necessary for the mockup or is a written description enough for you to move forward?
I can use the description for the mockup, or even your hand drawing

**Comment by SonQBChau** [comment]
About the dashboard layout, I'm not sure how to design it yet:
- We can throw everything into 1 page and call it a day, most people would do this
- Only show the graphs according to the type of questions (it helps if the questions are related)

**Comment by imtvwy** [comment]
> About the dashboard layout, I'm not sure how to design it yet:
> 
> * We can throw everything into 1 page and call it a day, most people would do this
Yes, I'd think so because this is what a dashboard should look (Data at-a-glance)

> * Only show the graphs according to the type of questions (it helps if the questions are related)
Say we have 4 questions, I'd imagine the page to be partitioned into 4 parts and with each showing 
- the corresponding questions/ans (static text)
- plot
_ interactive user controls   
Some would use a left/panel to show the interactive widgets, but I think it depends if all our 4 parts can share the same widgets.  For example, changing the a date filter would change all 4 plots at the same time

> * Do we want a map?
I don't think it is necessary

> * Do our dashboard just be data exploration? We just show the data from the table without any models or running predictions. I think we would do this but I want to double-check
Yes, I think dashboard is just an interface for displaying and analyzing data, not involving any prediction.

**Comment by BooleanJulien** [comment]
@SonQBChau regarding 2018 vs. now point you mentioned, the issue is that the Gapminder data we're looking at only goes until 2018 I believe, it's a bit of a stretch to say "now"

**Comment by SonQBChau** [comment]
Yea I didn't realize that. If you want to be precise, we can use the exact number then

**Comment by SonQBChau** [comment]
Question 3: Over the last hundred years, child mortality has dropped by an average of -400% for some high-income countries. For low-income countries, this number is: -400%, -200%, -100%, -50%.

Plot: 
- Bubble Charts
- Axes: Year range between 1918 and 2018 vs. child mortality rate
- Content: circle for each country, coloured by income and size in income

Interactivity: 
- Tooltips for each country
- Slider years

**Comment by shyan0903** [comment]
Question 4:
In 1918, the ratio of income per capita at the 75% percentile to that at the 25% percentile was X. How has that ratio changed in 2018? (possible answers: higher, lower, stays the same)

Plot:
scatter plot with lines
Axes: year vs. income per capita
Content: each point represents the averaged income per capita for a year for a chosen region, the default is all the countries; size can be used to compare value amount

Interactivity:
Slider: year range between 1918 and 2018
dropdown: filter by country or region and by income group
