### ISSUE TITLE
Peer review-group 13

### ISSUE THREAD

**Issue by SonQBChau** [UBC-MDS/gapminder_challenge#43]
Son-Frontend
Irene-Backend
Vanessa-Persona
Julien-Documentation

**Persona**
* Provide 3 pieces of constructive feedback that could help the app to be better suited to the scenario it was designed for
* Provide 3 pieces of constructive feedback that could help the app to be better suited to the user(persona) it was designed for

**Frontend / layout**
* Is the text (plot labels / titles / subtitles) easy to read? 
* Are the plots selected appropiated for the data? Can you think of other alternatives or improvements for the plots regarding interactivity/reactivity or plot selection?
* Was the dashboard organized in a way that was easy to read (columns / rows) or you would suggest a change in this sense?
* Would you prefer including tabs / navbars to improve the navigation or you think it is better to visualize everything in one screen by the nature of the content?
* Are the plots or other images described properly for the persona described?

**Backend**
* Are the options that you can select in the widgets working fine or have you found some cases where it is not working?
* If there are interactive plots: are the labels clear and easy to understand?

**Documentation**
* Was the documentation easy to understand from the `README.md` how to use the app? How could the documentation be improved?
* Was the app intuitive to use without reading the documentation? What information could be good to include? 

**Indicate something you would like to include in your own app after reviewing this one**

**Comment by shyan0903** [comment]
I have added my comments for the Backend section here: https://github.com/UBC-MDS/DSCI532-peer-review/issues/27

**Comment by BooleanJulien** [comment]
finished my part, added directly to their issue
