### ISSUE TITLE
Create repo for R

### ISSUE THREAD

**Issue by SonQBChau** [UBC-MDS/gapminder_challenge#44]

**Comment by shyan0903** [comment]
The repo has been created and here is the link: https://github.com/UBC-MDS/gapminder_challenge-R

**Comment by shyan0903** [comment]
I just created a PR for copying over the necessary files to the R app repo: https://github.com/UBC-MDS/gapminder_challenge-R/pull/2 Would some one take a look and merge it? Thanks!
