### ISSUE TITLE
Sketch the interface

### ISSUE THREAD

**Issue by SonQBChau** [UBC-MDS/gapminder_challenge#7]

**Comment by SonQBChau** [comment]
<img width="796" alt="Screen Shot 2022-02-16 at 11 46 25 AM" src="https://user-images.githubusercontent.com/12553570/154343989-ae7fe558-d5fc-4c8c-a6a9-845e0e4ed5f9.png">
@imtvwy How does it look?

**Comment by imtvwy** [comment]
Looks good.  It'd be great if you can change the wordings in button to "By Income Group", "By Region".  
If it is too difficult, I think we can explain with annotation on the sketch. Thanks @SonQBChau

**Comment by SonQBChau** [comment]
<img width="1153" alt="Screen Shot 2022-02-16 at 9 04 08 PM" src="https://user-images.githubusercontent.com/12553570/154409024-5e11cbc3-cb71-4a3c-b525-4517f2bef7e0.png">
I updated the sketch

**Comment by SonQBChau** [comment]
<img width="1021" alt="Screen Shot 2022-02-16 at 9 30 21 PM" src="https://user-images.githubusercontent.com/12553570/154411643-ad414e8f-bbe5-45ae-94bb-3ab9ab672331.png">
updated for Julien

**Comment by imtvwy** [comment]
Maybe adding an example of tooltip and legend for line charts?

**Comment by SonQBChau** [comment]
<img width="1362" alt="Screen Shot 2022-02-16 at 10 44 54 PM" src="https://user-images.githubusercontent.com/12553570/154420402-66add0c1-8cc1-4bfb-8064-b33fa4056dc5.png">
updated for Vanessa

**Comment by SonQBChau** [comment]
<img width="1060" alt="Screen Shot 2022-02-17 at 9 40 04 PM" src="https://user-images.githubusercontent.com/12553570/154624601-ee65cb86-af83-4500-888c-94455866f970.png">
updated for Irene
